steps:
- name: 'gcr.io/cloud-builders/docker'
  timeout: 86400s
  args: [ 'build', '-t', 'gcr.io/qwiklabs-gcp-02-b75d8a1cf514/dockerfile', '.' ]
  timeout: 86400s
timeout: 86400s

options:
  pool:
    name: 'projects/qwiklabs-gcp-02-b75d8a1cf514/locations/northamerica-northeast1/workerPools/MAIN'  
    
    


